stages:
  - build
  - test
  - deploy

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker-compose -f docker-compose.dev.yml build
  only:
    - master

test-db:
  stage: test
  script:
    - echo "This job tests the database."
    - pytest tests/test_db.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
