services:
  website:
    container_name: pub-website
    ports:
      - "5000:5000"
    build: 
      context: "website" 
      dockerfile: "Dockerfile.dev"
    environment:
      - ROTARY_SECRET_KEY=${SECRET_KEY}
      - ROTARY_DATABASE=/app/instance/rotary.sqlite
      - ROTARY_USERNAME=${USERNAME}
      - ROTARY_PASSWORD=${PASSWORD}
      - ROTARY_MARIADB_HOST=${MARIADB_HOST}
      - ROTARY_MARIADB_USER=${MARIADB_USER}
      - ROTARY_MARIADB_PASS=${MARIADB_PASS}
      - ROTARY_MARIADB_DB=${MARIADB_DB}
      - ROTARY_SMTP_PORT=587
      - ROTARY_SMTP_HOST=smtp.gmail.com
      - ROTARY_SMTP_USERNAME=${GOOGLE_USERNAME}
      - ROTARY_SMTP_PASSWORD=${GOOGLE_PASSWORD}
      - ROTARY_SMTP_CONTACT_FORM_ADDRESS=info@rotarypub.se
    volumes:
      - ./instance:/app/instance
      - ./secretKey.json:/app/rotary/secretKey.json:ro
      - ./website/rotary:/app/rotary
      - /app/rotary/static/css
      - /app/rotary/static/sass

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test123
      TZ: "Europe/Stockholm"
    volumes:
      - ./development/mariadb:/var/lib/mysql:Z
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
