services:
  website:
    container_name: pub-website
    build: website
    environment:
      - ROTARY_SECRET_KEY=${SECRET_KEY}
      - ROTARY_DATABASE=instance/rotary.sqlite
      - ROTARY_USERNAME=${USERNAME}
      - ROTARY_PASSWORD=${PASSWORD}
      - ROTARY_SMTP_PORT=587
      - ROTARY_SMTP_HOST=smtp.gmail.com
      - ROTARY_SMTP_USERNAME=${GOOGLE_USERNAME}
      - ROTARY_SMTP_PASSWORD=${GOOGLE_PASSWORD}
      - ROTARY_SMTP_CONTACT_FORM_ADDRESS=website@rotarypub.se
    volumes:
      - ./instance:/app/instance
    networks:
      - reverse-proxy
    restart: "no"

networks:
  reverse-proxy:
    external: true