services:
  website:
    container_name: pub-website
    build: 
      context: website
      dockerfile: Dockerfile.dev
    environment:
      - ROTARY_SECRET_KEY=dev
      - ROTARY_DATABASE=instance/rotary.sqlite
      - ROTARY_USERNAME=dev
      - ROTARY_PASSWORD=password
      - ROTARY_SMTP_PORT=587
      - ROTARY_SMTP_HOST=smtp.gmail.com
      - ROTARY_SMTP_USERNAME=${GOOGLE_USERNAME}
      - ROTARY_SMTP_PASSWORD=${GOOGLE_PASSWORD}
      - ROTARY_SMTP_CONTACT_FORM_ADDRESS=website@rotarypub.se
      - FLASK_APP=rotary
      - FLASK_ENV=development
    volumes:
      - ./instance:/app/instance
      - ./website/rotary:/app/rotary
      - /app/rotary/static/
    ports:
      - "5000:5000"

  