version: "3.1"
services:
  website:
    container_name: pub-website
    build: website
    environment:
      - ROTARY_USERNAME=${USERNAME}
      - ROTARY_PASSWORD=${PASSWORD}
      - ROTARY_SMTP_PORT=587
      - ROTARY_SMTP_HOST=smtp-relay.gmail.com
      - ROTARY_SMTP_USERNAME=user@host.com
      - ROTARY_SMTP_PASSWORD=password
      - ROTARY_SMTP_CONTACT_FORM_ADDRESS=user@host.com
    volumes:
      - ./instance:/app/instance
    networks:
      - reverse-proxy
    restart: "no"

networks:
  reverse-proxy:
    external: true
