FROM debian:bookworm AS dev

RUN ln -snf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime && \
    echo "Europe/Stockholm" > /etc/timezone && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-lang-european \
    nodejs \
    npm \ 
    bash
    
RUN apt-get install --no-install-recommends -y \
    python3 \
    python3.11-venv \
    python3-pip
    

RUN apt-get clean 


WORKDIR /app

COPY package.json .
RUN npm install 
WORKDIR /app

COPY . /app

RUN npm run build-css
RUN npm run purge-css

COPY ./rotary/static/css /app/rotary/static/css

RUN python3 -m venv .venv

ENV PATH="/app/.venv/bin:$PATH"

RUN python3 -m pip install \ 
    Flask \
    flask \
    flask_compress \
    flask-talisman \
    pycountry \
    mysql-connector-python

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV FLASK_APP=rotary



EXPOSE 5000
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
