FROM ubuntu:23.04

RUN ln -snf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime && \
    echo "Europe/Stockholm" > /etc/timezone && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    python3 \
    python3-pip \
    nodejs \
    npm \ 
    texlive-latex-base \
    texlive-latex-extra \
    texlive-lang-european && \
    apt-get clean

WORKDIR /app

COPY package.json /app/
RUN npm install

COPY setup.py /app/
RUN python3 setup.py install

COPY . /app

RUN npm run build-css
RUN npm run build-dataTables

EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--debug"]
